### ISSUE TITLE
+ button overlaps passwd

### ISSUE THREAD

**Issue by fenix011** [goexle/peanutEncryption#2]
... when you filled the screen with several of them.
In result, the _last one_ on screen can hardly be read.

thanks

**Comment by goexle** [comment]
Hi Jordila,
Thanks for your feedback.
Which resolution has your phone?
Would you mind sending me a screenshot?
Thanks!

**Comment by goexle** [comment]
Sorry, misunderstood your question. Now its clear what you mean.
I will fix it!
Thanks!

**Comment by fenix011** [comment]
thanks for the software
